/* Almoxarifado de equipamentos, filiais, empréstimos e movimentações. */
let almAba='equipamentos',almEquipamentos=[],almClientes=[],almUnidades=[],almEmprestimos=[],almMovimentos=[],almOrdens=[];
const almHoje=()=>new Date().toISOString().slice(0,10);
const almData=v=>v?new Date(v.length===10?`${v}T12:00:00`:v).toLocaleDateString('pt-BR'):'—';
const almDataHora=v=>v?new Date(v).toLocaleString('pt-BR'):'—';
const almIdent=e=>[e.tipo,e.marca,e.modelo].filter(Boolean).join(' · ')||'Equipamento';
const almSerie=e=>e.serial||e.patrimonio||'Sem identificação';
const almPodeEditar=()=>typeof cadPodeEditar==='function'&&cadPodeEditar();

function almInstalar(){
  if(!document.getElementById('almModalEquipamento'))document.body.insertAdjacentHTML('beforeend',almTemplates());
  const emprestado=[...document.querySelectorAll('#almEqStatus option')].find(x=>x.textContent==='Emprestado');if(emprestado)emprestado.disabled=true;
  window.cadRenderEquipamentos=almRender;
  window.gcAbrirModalEquipamento=almAbrirEquipamento;
  window.gcSalvarEquipamento=almSalvarEquipamento;
  if(window.lucide)lucide.createIcons();
}

function almTemplates(){return `
<div id="almModalEquipamento" class="crm-modal-overlay" onclick="if(event.target===this)almFechar('almModalEquipamento')"><div class="crm-modal-content alm-modal"><div class="modal-header"><div><h2 id="almEqTitulo">Novo equipamento</h2><p>Máquina identificada individualmente por série ou patrimônio.</p></div><button class="modal-close" onclick="almFechar('almModalEquipamento')">×</button></div><input id="almEqId" type="hidden"><div class="gc-form"><label>Proprietário *<select id="almEqProprietario" onchange="almAlternarProprietario()"><option>Help</option><option>Cliente</option></select></label><label id="almEqClienteBox">Cliente proprietário *<select id="almEqCliente" onchange="almAtualizarUnidades('almEqCliente','almEqUnidade')"></select></label><label>Tipo *<input id="almEqTipo" placeholder="Computador, notebook, monitor..."></label><label>Marca<input id="almEqMarca"></label><label>Modelo<input id="almEqModelo"></label><label>Número de série<input id="almEqSerial"></label><label>Patrimônio<input id="almEqPatrimonio"></label><label>Data de aquisição<input id="almEqAquisicao" type="date"></label><label>Garantia até<input id="almEqGarantia" type="date"></label><label>Status<select id="almEqStatus"><option>Disponível no almoxarifado</option><option>Em uso</option><option>Em manutenção</option><option>Em trânsito</option><option>Emprestado</option><option>Inativo</option></select></label><label id="almEqUnidadeBox">Filial / unidade<select id="almEqUnidade"></select></label><label>Localização atual<input id="almEqLocal" placeholder="Ex.: Oficina Help"></label><label>Responsável atual<input id="almEqResponsavel"></label><label>Condição<select id="almEqCondicao"><option>Novo</option><option selected>Bom</option><option>Com avarias</option><option>Danificado</option><option>Inoperante</option></select></label><label>Acessórios<input id="almEqAcessorios" placeholder="Fonte, carregador, mouse..."></label><label class="full">Observações<textarea id="almEqObs" rows="3"></textarea></label></div><div class="modal-footer"><button class="btn btn-secondary" onclick="almFechar('almModalEquipamento')">Cancelar</button><button class="btn btn-primary" onclick="almSalvarEquipamento()"><i data-lucide="save"></i>Salvar equipamento</button></div></div></div>
<div id="almModalMovimento" class="crm-modal-overlay" onclick="if(event.target===this)almFechar('almModalMovimento')"><div class="crm-modal-content alm-modal"><div class="modal-header"><div><h2>Movimentar equipamento</h2><p>Registre recebimentos, transferências e retornos.</p></div><button class="modal-close" onclick="almFechar('almModalMovimento')">×</button></div><div class="gc-form"><label class="full">Equipamento *<select id="almMovEquipamento" onchange="almPreencherOrigem()"></select></label><label>Tipo *<select id="almMovTipo" onchange="almSugerirStatusMovimento()"><option>Recebimento para manutenção</option><option>Transferência</option><option>Envio ao cliente</option><option>Retorno ao cliente</option><option>Retorno ao almoxarifado</option><option>Ajuste de localização</option></select></label><label>Novo status<select id="almMovStatus"><option>Em manutenção</option><option>Em trânsito</option><option>Em uso</option><option>Disponível no almoxarifado</option><option>Inativo</option></select></label><label>Cliente relacionado<select id="almMovCliente" onchange="almAtualizarUnidades('almMovCliente','almMovUnidade')"></select></label><label>Filial / unidade<select id="almMovUnidade"></select></label><label>OS vinculada<select id="almMovOs"></select></label><label>Responsável<input id="almMovResponsavel"></label><label>Origem<input id="almMovOrigem"></label><label>Destino *<input id="almMovDestino"></label><label>Condição<select id="almMovCondicao"><option>Novo</option><option selected>Bom</option><option>Com avarias</option><option>Danificado</option><option>Inoperante</option></select></label><label>Acessórios<input id="almMovAcessorios"></label><label class="full">Descrição / observações<textarea id="almMovDescricao" rows="3"></textarea></label></div><div class="modal-footer"><button class="btn btn-secondary" onclick="almFechar('almModalMovimento')">Cancelar</button><button class="btn btn-primary" onclick="almSalvarMovimento()"><i data-lucide="arrow-left-right"></i>Registrar movimentação</button></div></div></div>
<div id="almModalEmprestimo" class="crm-modal-overlay" onclick="if(event.target===this)almFechar('almModalEmprestimo')"><div class="crm-modal-content alm-modal"><div class="modal-header"><div><h2>Emprestar máquina reserva</h2><p>A máquina continuará sendo patrimônio da Help.</p></div><button class="modal-close" onclick="almFechar('almModalEmprestimo')">×</button></div><div class="gc-form"><label class="full">Máquina disponível *<select id="almEmpEquipamento"></select></label><label>Cliente *<select id="almEmpCliente" onchange="almAtualizarUnidades('almEmpCliente','almEmpUnidade')"></select></label><label>Filial / unidade<select id="almEmpUnidade"></select></label><label>Responsável *<input id="almEmpResponsavel" placeholder="Colaborador que recebeu"></label><label>Previsão de devolução<input id="almEmpPrevisao" type="date"></label><label>OS vinculada<select id="almEmpOs"></select></label><label>Condição na saída<select id="almEmpCondicao"><option>Novo</option><option selected>Bom</option><option>Com avarias</option></select></label><label>Acessórios entregues<input id="almEmpAcessorios"></label><label class="full">Motivo<input id="almEmpMotivo" placeholder="Uso enquanto a máquina original está em manutenção"></label><label class="full">Observações<textarea id="almEmpObs" rows="3"></textarea></label></div><div class="modal-footer"><button class="btn btn-secondary" onclick="almFechar('almModalEmprestimo')">Cancelar</button><button class="btn btn-primary" onclick="almSalvarEmprestimo()"><i data-lucide="handshake"></i>Registrar empréstimo</button></div></div></div>
<div id="almModalDevolucao" class="crm-modal-overlay" onclick="if(event.target===this)almFechar('almModalDevolucao')"><div class="crm-modal-content alm-modal"><div class="modal-header"><div><h2>Receber devolução</h2><p>Confira a máquina e os acessórios antes de finalizar.</p></div><button class="modal-close" onclick="almFechar('almModalDevolucao')">×</button></div><input id="almDevId" type="hidden"><div class="gc-form"><label>Condição no retorno<select id="almDevCondicao"><option>Bom</option><option>Com avarias</option><option>Danificado</option><option>Inoperante</option></select></label><label>Acessórios devolvidos<input id="almDevAcessorios"></label><label>Local de retorno<input id="almDevLocal" value="Almoxarifado Help"></label><label class="full">Observações<textarea id="almDevObs" rows="3"></textarea></label></div><div class="modal-footer"><button class="btn btn-secondary" onclick="almFechar('almModalDevolucao')">Cancelar</button><button class="btn btn-primary" onclick="almSalvarDevolucao()"><i data-lucide="package-check"></i>Confirmar devolução</button></div></div></div>
<div id="almModalUnidades" class="crm-modal-overlay" onclick="if(event.target===this)almFechar('almModalUnidades')"><div class="crm-modal-content alm-modal"><div class="modal-header"><div><h2>Filiais e unidades</h2><p>Organize matriz e filiais dentro do mesmo cliente.</p></div><button class="modal-close" onclick="almFechar('almModalUnidades')">×</button></div><div class="gc-form"><label class="full">Cliente *<select id="almUniCliente" onchange="almRenderUnidadesModal()"></select></label></div><div id="almUnidadesLista" class="alm-unidades-lista"></div><input id="almUniId" type="hidden"><div class="gc-form alm-unidade-form"><label>Nome da unidade *<input id="almUniNome" placeholder="Matriz, Bonito, Miranda..."></label><label>Cidade<input id="almUniCidade"></label><label>UF<input id="almUniUf" maxlength="2"></label><label class="full">Endereço<input id="almUniEndereco"></label><label class="cad-check"><input id="almUniPrincipal" type="checkbox"><span>Unidade principal</span></label><label class="cad-check"><input id="almUniAtiva" type="checkbox" checked><span>Unidade ativa</span></label></div><div class="modal-footer"><button class="btn btn-secondary" onclick="almLimparUnidade()">Limpar</button><button class="btn btn-primary" onclick="almSalvarUnidade()"><i data-lucide="save"></i>Salvar filial</button></div></div></div>`}

async function almCarregar(){
  const[e,c,u,em,m,os]=await Promise.all([
    supabaseClient.from('equipamentos').select('*,clientes!equipamentos_cliente_id_fkey(nome),cliente_unidades(nome,cidade,uf)').eq('ativo',true).order('criado_em',{ascending:false}),
    supabaseClient.from('clientes').select('id,nome,unidade,cidade,uf').eq('eh_cliente',true).order('nome'),
    supabaseClient.from('cliente_unidades').select('*').order('nome'),
    supabaseClient.from('equipamento_emprestimos').select('*,equipamentos(tipo,marca,modelo,serial,patrimonio),clientes(nome),cliente_unidades(nome),ordens_servico(numero)').order('criado_em',{ascending:false}),
    supabaseClient.from('equipamento_movimentacoes').select('*,equipamentos(tipo,marca,modelo,serial,patrimonio),clientes(nome),cliente_unidades(nome),ordens_servico(numero)').order('ocorrido_em',{ascending:false}).limit(100),
    supabaseClient.from('ordens_servico').select('id,numero,cliente,status').neq('status','Cancelada').order('criado_em',{ascending:false}).limit(200)
  ]);
  const erro=[e,c,u,em,m,os].find(x=>x.error)?.error;if(erro)throw erro;
  almEquipamentos=e.data||[];almClientes=c.data||[];almUnidades=u.data||[];almEmprestimos=em.data||[];almMovimentos=m.data||[];almOrdens=os.data||[];gcEquipamentos=almEquipamentos;gcClientes=almClientes;
}

async function almRender(){
  const el=document.getElementById('cadEquipamentosConteudo');if(!el)return;el.innerHTML='<div class="cad-loading">Carregando almoxarifado...</div>';
  try{await almCarregar()}catch(e){el.innerHTML=`<div class="cad-empty">Não foi possível carregar equipamentos: ${cadHtml(e.message)}</div>`;return}
  const ativos=almEmprestimos.filter(x=>['Ativo','Aguardando devolução'].includes(x.status)),hoje=almHoje(),vencidos=ativos.filter(x=>x.previsao_devolucao&&x.previsao_devolucao<hoje),disponiveis=almEquipamentos.filter(x=>x.proprietario_tipo==='Help'&&!x.emprestado&&x.status==='Disponível no almoxarifado');
  el.innerHTML=`<div class="cad-head"><div><span>ALMOXARIFADO</span><h2>Equipamentos, empréstimos e garantias</h2><p>Controle máquinas da Help e dos clientes, incluindo filiais, manutenção e reservas.</p></div><div class="actions">${almPodeEditar()?'<button class="btn btn-secondary" onclick="almAbrirUnidades()"><i data-lucide="building-2"></i>Filiais</button><button class="btn btn-secondary" onclick="almAbrirMovimento()"><i data-lucide="arrow-left-right"></i>Movimentar</button><button class="btn btn-secondary" onclick="almAbrirEmprestimo()"><i data-lucide="handshake"></i>Emprestar reserva</button><button class="btn btn-primary" onclick="almAbrirEquipamento()"><i data-lucide="monitor-up"></i>Novo equipamento</button>':''}</div></div><div class="cad-kpis alm-kpis"><article><span>Máquinas cadastradas</span><b>${almEquipamentos.length}</b></article><article><span>Reservas disponíveis</span><b>${disponiveis.length}</b></article><article class="${ativos.length?'alerta':''}"><span>Emprestadas</span><b>${ativos.length}</b></article><article class="${vencidos.length?'perigo':''}"><span>Devoluções atrasadas</span><b>${vencidos.length}</b></article></div><nav class="alm-tabs"><button class="${almAba==='equipamentos'?'active':''}" onclick="almTrocarAba('equipamentos')"><i data-lucide="monitor-cog"></i>Equipamentos</button><button class="${almAba==='almoxarifado'?'active':''}" onclick="almTrocarAba('almoxarifado')"><i data-lucide="warehouse"></i>Almoxarifado</button><button class="${almAba==='emprestimos'?'active':''}" onclick="almTrocarAba('emprestimos')"><i data-lucide="handshake"></i>Empréstimos</button><button class="${almAba==='movimentacoes'?'active':''}" onclick="almTrocarAba('movimentacoes')"><i data-lucide="history"></i>Movimentações</button></nav><div id="almConteudo"></div>`;
  almRenderAba();if(window.lucide)lucide.createIcons();
}
function almTrocarAba(aba){almAba=aba;document.querySelectorAll('.alm-tabs button').forEach(x=>x.classList.toggle('active',x.getAttribute('onclick').includes(`'${aba}'`)));almRenderAba()}
function almRenderAba(){if(almAba==='equipamentos')almRenderEquipamentos();if(almAba==='almoxarifado')almRenderAlmoxarifado();if(almAba==='emprestimos')almRenderEmprestimos();if(almAba==='movimentacoes')almRenderMovimentos();if(window.lucide)lucide.createIcons()}
function almRenderEquipamentos(){
  const el=document.getElementById('almConteudo');el.innerHTML=`<div class="cad-busca cad-busca-unica"><i data-lucide="search"></i><input id="almBuscaEquip" placeholder="Buscar máquina, série, patrimônio, cliente ou filial" oninput="almFiltrarEquipamentos()"></div><div id="almTabelaEquip"></div>`;almFiltrarEquipamentos();
}
function almFiltrarEquipamentos(){const busca=(document.getElementById('almBuscaEquip')?.value||'').toLowerCase(),lista=almEquipamentos.filter(e=>!busca||`${almIdent(e)} ${almSerie(e)} ${e.clientes?.nome||e.cliente_nome} ${e.cliente_unidades?.nome||''} ${e.localizacao}`.toLowerCase().includes(busca)),el=document.getElementById('almTabelaEquip');if(!el)return;el.innerHTML=`<div class="cad-table-wrap"><table class="cad-table alm-table"><thead><tr><th>Equipamento</th><th>Proprietário</th><th>Localização atual</th><th>Status</th><th>Garantia</th><th>Ações</th></tr></thead><tbody>${lista.map(e=>`<tr><td><b>${cadHtml(almIdent(e))}</b><small>${cadHtml(almSerie(e))}</small></td><td><span class="alm-owner ${e.proprietario_tipo==='Help'?'help':'cliente'}">${cadHtml(e.proprietario_tipo)}</span><small>${e.proprietario_tipo==='Cliente'?cadHtml(e.clientes?.nome||e.cliente_nome):'Help Soluções Tecnológicas'}</small></td><td><b>${cadHtml(e.localizacao||'—')}</b><small>${cadHtml([e.cliente_unidades?.nome,e.responsavel_nome].filter(Boolean).join(' · '))}</small></td><td><span class="alm-status ${e.emprestado?'emprestado':''}">${cadHtml(e.status)}</span></td><td>${e.garantia_ate?`<span class="cad-garantia ${e.garantia_ate<almHoje()?'vencida':''}">${almData(e.garantia_ate)}</span>`:'Sem garantia'}</td><td><div class="cad-acoes">${almPodeEditar()?`<button title="Editar" onclick="almAbrirEquipamento(${e.id})"><i data-lucide="pencil"></i></button>${!e.emprestado?`<button title="Movimentar" onclick="almAbrirMovimento(${e.id})"><i data-lucide="arrow-left-right"></i></button>`:''}${e.proprietario_tipo==='Help'&&!e.emprestado?`<button title="Emprestar reserva" onclick="almAbrirEmprestimo(${e.id})"><i data-lucide="handshake"></i></button>`:''}`:''}</div></td></tr>`).join('')||'<tr><td colspan="6" class="cad-empty">Nenhum equipamento encontrado.</td></tr>'}</tbody></table></div>`;if(window.lucide)lucide.createIcons()}
function almRenderAlmoxarifado(){const lista=almEquipamentos.filter(e=>e.proprietario_tipo==='Help');document.getElementById('almConteudo').innerHTML=`<div class="alm-cards">${lista.map(e=>`<article class="alm-card ${e.emprestado?'fora':''}"><div><span>${cadHtml(e.status)}</span><h3>${cadHtml(almIdent(e))}</h3><p>${cadHtml(almSerie(e))}</p></div><dl><div><dt>Local</dt><dd>${cadHtml(e.localizacao||'Almoxarifado Help')}</dd></div><div><dt>Condição</dt><dd>${cadHtml(e.condicao||'—')}</dd></div><div><dt>Acessórios</dt><dd>${cadHtml(e.acessorios||'—')}</dd></div></dl>${almPodeEditar()&&!e.emprestado?`<button class="btn btn-primary" onclick="almAbrirEmprestimo(${e.id})"><i data-lucide="handshake"></i>Emprestar</button>`:''}</article>`).join('')||'<div class="cad-empty">Nenhuma máquina própria cadastrada no almoxarifado.</div>'}</div>`}
function almRenderEmprestimos(){const hoje=almHoje();document.getElementById('almConteudo').innerHTML=`<div class="cad-table-wrap"><table class="cad-table alm-table"><thead><tr><th>Empréstimo</th><th>Máquina</th><th>Cliente / filial</th><th>Responsável</th><th>Saída / previsão</th><th>Status</th><th>Ações</th></tr></thead><tbody>${almEmprestimos.map(e=>{const atrasado=['Ativo','Aguardando devolução'].includes(e.status)&&e.previsao_devolucao&&e.previsao_devolucao<hoje;return `<tr><td><b>${cadHtml(e.numero)}</b><small>${e.ordens_servico?.numero?`OS ${cadHtml(e.ordens_servico.numero)}`:'Sem OS'}</small></td><td><b>${cadHtml(almIdent(e.equipamentos||{}))}</b><small>${cadHtml(almSerie(e.equipamentos||{}))}</small></td><td><b>${cadHtml(e.clientes?.nome)}</b><small>${cadHtml(e.cliente_unidades?.nome||'—')}</small></td><td>${cadHtml(e.responsavel_nome)}</td><td>${almDataHora(e.data_saida)}<small class="${atrasado?'alm-atrasado':''}">Previsão: ${almData(e.previsao_devolucao)}</small></td><td><span class="alm-status ${atrasado?'atrasado':''}">${atrasado?'Atrasado':cadHtml(e.status)}</span></td><td><div class="cad-acoes"><button title="Termo de empréstimo" onclick="almImprimirTermo(${e.id})"><i data-lucide="file-down"></i></button>${almPodeEditar()&&['Ativo','Aguardando devolução'].includes(e.status)?`<button title="Receber devolução" onclick="almAbrirDevolucao(${e.id})"><i data-lucide="package-check"></i></button>`:''}</div></td></tr>`}).join('')||'<tr><td colspan="7" class="cad-empty">Nenhum empréstimo registrado.</td></tr>'}</tbody></table></div>`}
function almRenderMovimentos(){document.getElementById('almConteudo').innerHTML=`<div class="alm-timeline">${almMovimentos.map(m=>`<article><i><i data-lucide="${m.tipo==='Empréstimo'?'handshake':m.tipo==='Devolução'?'package-check':'arrow-left-right'}"></i></i><div><b>${cadHtml(m.tipo)} · ${cadHtml(almIdent(m.equipamentos||{}))}</b><p>${cadHtml(m.origem||'—')} → ${cadHtml(m.destino||'—')}</p><small>${cadHtml([m.clientes?.nome,m.cliente_unidades?.nome,m.ordens_servico?.numero,m.responsavel_nome].filter(Boolean).join(' · '))}</small>${m.descricao?`<small>${cadHtml(m.descricao)}</small>`:''}</div><time>${almDataHora(m.ocorrido_em)}</time></article>`).join('')||'<div class="cad-empty">Nenhuma movimentação registrada.</div>'}</div>`}

function almOpcoesClientes(vazio='Selecione'){return `<option value="">${vazio}</option>`+almClientes.map(c=>`<option value="${c.id}">${cadHtml(c.nome)}</option>`).join('')}
function almOpcoesOs(){return '<option value="">Sem vínculo</option>'+almOrdens.map(o=>`<option value="${o.id}">${cadHtml(o.numero)} · ${cadHtml(o.cliente)}</option>`).join('')}
function almAtualizarUnidades(clienteEl,unidadeEl,selecionado=''){const cliente=Number(document.getElementById(clienteEl)?.value),el=document.getElementById(unidadeEl);if(!el)return;el.innerHTML='<option value="">Sem filial</option>'+almUnidades.filter(u=>u.ativo&&Number(u.cliente_id)===cliente).map(u=>`<option value="${u.id}" ${Number(u.id)===Number(selecionado)?'selected':''}>${cadHtml(u.nome)}${u.cidade?' · '+cadHtml(u.cidade):''}</option>`).join('')}
function almFechar(id){document.getElementById(id)?.classList.remove('active')}

function almAbrirEquipamento(id=null){const e=almEquipamentos.find(x=>Number(x.id)===Number(id))||{},cliente=e.proprietario_tipo==='Cliente'?(e.proprietario_cliente_id||e.cliente_id):'';document.getElementById('almEqTitulo').textContent=e.id?'Editar equipamento':'Novo equipamento';document.getElementById('almEqId').value=e.id||'';document.getElementById('almEqProprietario').value=e.proprietario_tipo||'Help';document.getElementById('almEqCliente').innerHTML=almOpcoesClientes();document.getElementById('almEqCliente').value=cliente||'';almAtualizarUnidades('almEqCliente','almEqUnidade',e.unidade_id);const dados={almEqTipo:e.tipo||'',almEqMarca:e.marca||'',almEqModelo:e.modelo||'',almEqSerial:e.serial||'',almEqPatrimonio:e.patrimonio||'',almEqAquisicao:e.data_aquisicao||'',almEqGarantia:e.garantia_ate||'',almEqStatus:e.status||(e.proprietario_tipo==='Cliente'?'Em uso':'Disponível no almoxarifado'),almEqLocal:e.localizacao||'',almEqResponsavel:e.responsavel_nome||'',almEqCondicao:e.condicao||'Bom',almEqAcessorios:e.acessorios||'',almEqObs:e.observacoes||''};Object.entries(dados).forEach(([k,v])=>document.getElementById(k).value=v);almAlternarProprietario();document.getElementById('almModalEquipamento').classList.add('active');if(window.lucide)lucide.createIcons()}
function almAlternarProprietario(){const cliente=document.getElementById('almEqProprietario').value==='Cliente';document.getElementById('almEqClienteBox').classList.toggle('hidden',!cliente);document.getElementById('almEqUnidadeBox').classList.toggle('hidden',!cliente);if(!cliente&&document.getElementById('almEqStatus').value==='Em uso')document.getElementById('almEqStatus').value='Disponível no almoxarifado'}
async function almSalvarEquipamento(){if(!almPodeEditar())return avisarModulo('Você não possui permissão para alterar equipamentos.');const id=Number(document.getElementById('almEqId').value)||null,proprietario=document.getElementById('almEqProprietario').value,clienteId=proprietario==='Cliente'?Number(document.getElementById('almEqCliente').value)||null:null,cliente=almClientes.find(c=>Number(c.id)===clienteId),tipo=document.getElementById('almEqTipo').value.trim();if(!tipo)return avisarModulo('Informe o tipo do equipamento.');if(proprietario==='Cliente'&&!clienteId)return avisarModulo('Escolha o cliente proprietário.');const p={proprietario_tipo:proprietario,proprietario_cliente_id:clienteId,cliente_id:clienteId,cliente_nome:cliente?.nome||'Estoque interno',unidade_id:clienteId?Number(document.getElementById('almEqUnidade').value)||null:null,tipo,marca:document.getElementById('almEqMarca').value.trim(),modelo:document.getElementById('almEqModelo').value.trim(),serial:document.getElementById('almEqSerial').value.trim(),patrimonio:document.getElementById('almEqPatrimonio').value.trim(),data_aquisicao:document.getElementById('almEqAquisicao').value||null,garantia_ate:document.getElementById('almEqGarantia').value||null,status:document.getElementById('almEqStatus').value,localizacao:document.getElementById('almEqLocal').value.trim()||(proprietario==='Help'?'Almoxarifado Help':cliente?.nome||''),responsavel_nome:document.getElementById('almEqResponsavel').value.trim(),condicao:document.getElementById('almEqCondicao').value,acessorios:document.getElementById('almEqAcessorios').value.trim(),observacoes:document.getElementById('almEqObs').value.trim(),emprestado:document.getElementById('almEqStatus').value==='Emprestado',atualizado_em:new Date().toISOString()};const q=id?supabaseClient.from('equipamentos').update(p).eq('id',id):supabaseClient.from('equipamentos').insert({...p,criado_por:usuarioLogado.id}),{error}=await q;if(error)return avisarModulo(error.message);almFechar('almModalEquipamento');await almRender();avisarModulo('Equipamento salvo com sucesso.')}

function almAbrirMovimento(id=null){document.getElementById('almMovEquipamento').innerHTML=almEquipamentos.filter(e=>!e.emprestado).map(e=>`<option value="${e.id}">${cadHtml(almIdent(e))} · ${cadHtml(almSerie(e))}</option>`).join('');if(id)document.getElementById('almMovEquipamento').value=id;document.getElementById('almMovCliente').innerHTML=almOpcoesClientes('Sem cliente');document.getElementById('almMovOs').innerHTML=almOpcoesOs();['almMovDestino','almMovResponsavel','almMovAcessorios','almMovDescricao'].forEach(x=>document.getElementById(x).value='');almPreencherOrigem();almAtualizarUnidades('almMovCliente','almMovUnidade');almSugerirStatusMovimento();document.getElementById('almModalMovimento').classList.add('active')}
function almPreencherOrigem(){const e=almEquipamentos.find(x=>Number(x.id)===Number(document.getElementById('almMovEquipamento').value));document.getElementById('almMovOrigem').value=e?.localizacao||'';document.getElementById('almMovCondicao').value=e?.condicao||'Bom';document.getElementById('almMovAcessorios').value=e?.acessorios||'';if(e?.cliente_id){document.getElementById('almMovCliente').value=e.cliente_id;almAtualizarUnidades('almMovCliente','almMovUnidade',e.unidade_id)}}
function almSugerirStatusMovimento(){const mapa={'Recebimento para manutenção':'Em manutenção','Transferência':'Em trânsito','Envio ao cliente':'Em uso','Retorno ao cliente':'Em uso','Retorno ao almoxarifado':'Disponível no almoxarifado','Ajuste de localização':'Em uso'};document.getElementById('almMovStatus').value=mapa[document.getElementById('almMovTipo').value]||'Em uso'}
async function almSalvarMovimento(){const p={p_equipamento_id:Number(document.getElementById('almMovEquipamento').value),p_tipo:document.getElementById('almMovTipo').value,p_origem:document.getElementById('almMovOrigem').value.trim(),p_destino:document.getElementById('almMovDestino').value.trim(),p_cliente_id:Number(document.getElementById('almMovCliente').value)||null,p_unidade_id:Number(document.getElementById('almMovUnidade').value)||null,p_os_id:Number(document.getElementById('almMovOs').value)||null,p_status_novo:document.getElementById('almMovStatus').value,p_responsavel_nome:document.getElementById('almMovResponsavel').value.trim(),p_condicao:document.getElementById('almMovCondicao').value,p_acessorios:document.getElementById('almMovAcessorios').value.trim(),p_descricao:document.getElementById('almMovDescricao').value.trim()};if(!p.p_equipamento_id||!p.p_destino)return avisarModulo('Informe o equipamento e o destino.');const{error}=await supabaseClient.rpc('movimentar_equipamento',p);if(error)return avisarModulo(error.message);almFechar('almModalMovimento');await almRender();avisarModulo('Movimentação registrada.')}

function almAbrirEmprestimo(id=null){const disp=almEquipamentos.filter(e=>e.proprietario_tipo==='Help'&&!e.emprestado&&e.status==='Disponível no almoxarifado');if(!disp.length)return avisarModulo('Não há máquinas da Help disponíveis no almoxarifado para empréstimo.');document.getElementById('almEmpEquipamento').innerHTML=disp.map(e=>`<option value="${e.id}">${cadHtml(almIdent(e))} · ${cadHtml(almSerie(e))} · ${cadHtml(e.status)}</option>`).join('');if(id)document.getElementById('almEmpEquipamento').value=id;document.getElementById('almEmpCliente').innerHTML=almOpcoesClientes();document.getElementById('almEmpOs').innerHTML=almOpcoesOs();['almEmpResponsavel','almEmpAcessorios','almEmpMotivo','almEmpObs'].forEach(x=>document.getElementById(x).value='');document.getElementById('almEmpPrevisao').value='';almAtualizarUnidades('almEmpCliente','almEmpUnidade');document.getElementById('almModalEmprestimo').classList.add('active')}
async function almSalvarEmprestimo(){const p={p_equipamento_id:Number(document.getElementById('almEmpEquipamento').value),p_cliente_id:Number(document.getElementById('almEmpCliente').value),p_unidade_id:Number(document.getElementById('almEmpUnidade').value)||null,p_os_id:Number(document.getElementById('almEmpOs').value)||null,p_responsavel_nome:document.getElementById('almEmpResponsavel').value.trim(),p_previsao_devolucao:document.getElementById('almEmpPrevisao').value||null,p_motivo:document.getElementById('almEmpMotivo').value.trim(),p_condicao_saida:document.getElementById('almEmpCondicao').value,p_acessorios_saida:document.getElementById('almEmpAcessorios').value.trim(),p_observacoes:document.getElementById('almEmpObs').value.trim()};if(!p.p_equipamento_id||!p.p_cliente_id||!p.p_responsavel_nome)return avisarModulo('Informe máquina, cliente e responsável.');const{error}=await supabaseClient.rpc('registrar_emprestimo_equipamento',p);if(error)return avisarModulo(error.message);almFechar('almModalEmprestimo');almAba='emprestimos';await almRender();avisarModulo('Máquina reserva emprestada com sucesso.')}
function almAbrirDevolucao(id){const e=almEmprestimos.find(x=>Number(x.id)===Number(id));if(!e)return;document.getElementById('almDevId').value=id;document.getElementById('almDevCondicao').value=e.condicao_saida||'Bom';document.getElementById('almDevAcessorios').value=e.acessorios_saida||'';document.getElementById('almDevObs').value='';document.getElementById('almDevLocal').value='Almoxarifado Help';document.getElementById('almModalDevolucao').classList.add('active')}
async function almSalvarDevolucao(){const{error}=await supabaseClient.rpc('devolver_emprestimo_equipamento',{p_emprestimo_id:Number(document.getElementById('almDevId').value),p_condicao_retorno:document.getElementById('almDevCondicao').value,p_acessorios_retorno:document.getElementById('almDevAcessorios').value.trim(),p_observacoes:document.getElementById('almDevObs').value.trim(),p_local_retorno:document.getElementById('almDevLocal').value.trim()});if(error)return avisarModulo(error.message);almFechar('almModalDevolucao');await almRender();avisarModulo('Devolução concluída. A máquina está disponível no almoxarifado.')}

function almAbrirUnidades(clienteId=null){document.getElementById('almUniCliente').innerHTML=almOpcoesClientes();if(clienteId)document.getElementById('almUniCliente').value=clienteId;almLimparUnidade();almRenderUnidadesModal();document.getElementById('almModalUnidades').classList.add('active')}
function almRenderUnidadesModal(){const id=Number(document.getElementById('almUniCliente').value),lista=almUnidades.filter(u=>Number(u.cliente_id)===id),el=document.getElementById('almUnidadesLista');el.innerHTML=lista.map(u=>`<button onclick="almEditarUnidade(${u.id})"><span><b>${cadHtml(u.nome)}</b><small>${cadHtml([u.cidade,u.uf].filter(Boolean).join('/'))}</small></span><span>${u.principal?'Principal':u.ativo?'Ativa':'Inativa'}</span></button>`).join('')||'<p class="cad-empty">Nenhuma filial cadastrada para este cliente.</p>';if(window.lucide)lucide.createIcons()}
function almEditarUnidade(id){const u=almUnidades.find(x=>Number(x.id)===Number(id));if(!u)return;document.getElementById('almUniId').value=u.id;document.getElementById('almUniNome').value=u.nome;document.getElementById('almUniCidade').value=u.cidade;document.getElementById('almUniUf').value=u.uf;document.getElementById('almUniEndereco').value=u.endereco;document.getElementById('almUniPrincipal').checked=u.principal;document.getElementById('almUniAtiva').checked=u.ativo}
function almLimparUnidade(){document.getElementById('almUniId').value='';['almUniNome','almUniCidade','almUniUf','almUniEndereco'].forEach(x=>document.getElementById(x).value='');document.getElementById('almUniPrincipal').checked=false;document.getElementById('almUniAtiva').checked=true}
async function almSalvarUnidade(){const p={p_id:Number(document.getElementById('almUniId').value)||null,p_cliente_id:Number(document.getElementById('almUniCliente').value),p_nome:document.getElementById('almUniNome').value.trim(),p_cidade:document.getElementById('almUniCidade').value.trim(),p_uf:document.getElementById('almUniUf').value.trim(),p_endereco:document.getElementById('almUniEndereco').value.trim(),p_principal:document.getElementById('almUniPrincipal').checked,p_ativo:document.getElementById('almUniAtiva').checked};if(!p.p_cliente_id||!p.p_nome)return avisarModulo('Escolha o cliente e informe o nome da filial.');const{error}=await supabaseClient.rpc('salvar_cliente_unidade',p);if(error)return avisarModulo(error.message);await almCarregar();almLimparUnidade();almRenderUnidadesModal();avisarModulo('Filial salva com sucesso.')}

function almImprimirTermo(id){const e=almEmprestimos.find(x=>Number(x.id)===Number(id));if(!e)return;const corpo=`<!doctype html><html><head><meta charset="utf-8"><title>${cadHtml(e.numero)}</title><style>body{font:14px Arial;color:#172033;margin:44px;line-height:1.55}h1{color:#1769e0;margin-bottom:2px}h2{margin-top:36px}.linha{display:flex;justify-content:space-between;border-bottom:1px solid #ddd;padding:10px 0}.assinaturas{display:grid;grid-template-columns:1fr 1fr;gap:50px;margin-top:90px}.ass{border-top:1px solid #444;text-align:center;padding-top:8px}.alerta{margin:24px 0;padding:14px;background:#eef5ff;border-left:4px solid #1769e0}</style></head><body><h1>Help Soluções Tecnológicas</h1><b>Termo de empréstimo de equipamento</b><h2>${cadHtml(e.numero)}</h2><div class="linha"><span>Cliente</span><b>${cadHtml(e.clientes?.nome)}</b></div><div class="linha"><span>Filial</span><b>${cadHtml(e.cliente_unidades?.nome||'—')}</b></div><div class="linha"><span>Responsável</span><b>${cadHtml(e.responsavel_nome)}</b></div><div class="linha"><span>Equipamento</span><b>${cadHtml(almIdent(e.equipamentos||{}))}</b></div><div class="linha"><span>Série / patrimônio</span><b>${cadHtml(almSerie(e.equipamentos||{}))}</b></div><div class="linha"><span>Data da saída</span><b>${almDataHora(e.data_saida)}</b></div><div class="linha"><span>Previsão de devolução</span><b>${almData(e.previsao_devolucao)}</b></div><div class="linha"><span>Condição</span><b>${cadHtml(e.condicao_saida)}</b></div><div class="linha"><span>Acessórios</span><b>${cadHtml(e.acessorios_saida||'—')}</b></div><p class="alerta">O equipamento permanece propriedade da Help Soluções Tecnológicas e deve ser devolvido nas condições registradas, juntamente com os acessórios informados.</p><p><b>Motivo:</b> ${cadHtml(e.motivo||'—')}</p><p><b>Observações:</b> ${cadHtml(e.observacoes||'—')}</p><div class="assinaturas"><div class="ass">Help Soluções Tecnológicas</div><div class="ass">${cadHtml(e.responsavel_nome)}</div></div><script>window.onload=()=>window.print()<\/script></body></html>`,w=window.open('','_blank');w.document.write(corpo);w.document.close()}

document.addEventListener('DOMContentLoaded',almInstalar);
