create table if not exists public.catalogo_itens (
  id bigint generated by default as identity primary key,
  tipo text not null,
  codigo text not null,
  descricao text not null,
  categoria text not null default '',
  unidade text not null default 'UN',
  custo numeric(14,2) not null default 0,
  preco_venda numeric(14,2) not null default 0,
  observacoes text not null default '',
  ativo boolean not null default true,
  criado_por uuid default auth.uid(),
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now(),
  constraint catalogo_itens_tipo_check check (tipo in ('Produto','Serviço')),
  constraint catalogo_itens_codigo_key unique (codigo),
  constraint catalogo_itens_valores_check check (custo >= 0 and preco_venda >= 0)
);

create index if not exists catalogo_itens_tipo_ativo_idx on public.catalogo_itens (tipo, ativo);
create index if not exists catalogo_itens_descricao_idx on public.catalogo_itens (descricao);
alter table public.catalogo_itens enable row level security;
grant select, insert, update, delete on public.catalogo_itens to authenticated;
grant usage, select on sequence public.catalogo_itens_id_seq to authenticated;

drop policy if exists "Equipe visualiza catalogo" on public.catalogo_itens;
create policy "Equipe visualiza catalogo" on public.catalogo_itens for select to authenticated
using ((select private.crm_tem_permissao('clientes')) or (select private.crm_tem_permissao('crm')) or (select private.crm_tem_permissao('os')));

drop policy if exists "Equipe cria catalogo" on public.catalogo_itens;
create policy "Equipe cria catalogo" on public.catalogo_itens for insert to authenticated
with check (((select private.crm_tem_permissao('crm')) or (select private.crm_tem_permissao('osCriar')) or (select private.crm_tem_permissao('osEditar'))) and criado_por = (select auth.uid()));

drop policy if exists "Equipe atualiza catalogo" on public.catalogo_itens;
create policy "Equipe atualiza catalogo" on public.catalogo_itens for update to authenticated
using ((select private.crm_tem_permissao('crm')) or (select private.crm_tem_permissao('osCriar')) or (select private.crm_tem_permissao('osEditar')))
with check ((select private.crm_tem_permissao('crm')) or (select private.crm_tem_permissao('osCriar')) or (select private.crm_tem_permissao('osEditar')));

drop policy if exists "Equipe exclui catalogo" on public.catalogo_itens;
create policy "Equipe exclui catalogo" on public.catalogo_itens for delete to authenticated
using ((select private.crm_tem_permissao('crm')) or (select private.crm_tem_permissao('osExcluir')));

alter table public.financeiro_recorrencias add column if not exists cancelada_em timestamptz;
alter table public.financeiro_recorrencias add column if not exists cancelado_por uuid;

drop policy if exists "Financeiro altera financeiro_recorrencias" on public.financeiro_recorrencias;
create policy "Financeiro altera financeiro_recorrencias" on public.financeiro_recorrencias for update to authenticated
using ((select private.crm_tem_permissao('financeiroCriar')) or (select private.crm_tem_permissao('financeiroExcluir')))
with check ((select private.crm_tem_permissao('financeiroCriar')) or (select private.crm_tem_permissao('financeiroExcluir')));

drop policy if exists "Financeiro altera lancamentos" on public.financeiro_lancamentos;
create policy "Financeiro altera lancamentos" on public.financeiro_lancamentos for update to authenticated
using ((select private.crm_tem_permissao('financeiroCriar')) or (select private.crm_tem_permissao('financeiroBaixar')) or (select private.crm_tem_permissao('financeiroExcluir')))
with check ((select private.crm_tem_permissao('financeiroCriar')) or (select private.crm_tem_permissao('financeiroBaixar')) or (select private.crm_tem_permissao('financeiroExcluir')));

create or replace function public.cancelar_financeiro_recorrencia(p_recorrencia_id bigint)
returns table (recorrencia_cancelada boolean, lancamentos_cancelados bigint)
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_lancamentos bigint := 0;
begin
  if (select auth.uid()) is null or not private.crm_tem_permissao('financeiroExcluir') then
    raise exception 'Você não possui permissão para cancelar recorrências.' using errcode = '42501';
  end if;

  update public.financeiro_recorrencias
     set ativa = false,
         cancelada_em = now(),
         cancelado_por = (select auth.uid()),
         atualizado_em = now()
   where id = p_recorrencia_id;

  if not found then
    return query select false, 0::bigint;
    return;
  end if;

  update public.financeiro_lancamentos
     set status = 'Cancelado',
         atualizado_em = now()
   where recorrencia_id = p_recorrencia_id
     and status = 'Pendente';
  get diagnostics v_lancamentos = row_count;

  return query select true, v_lancamentos;
end;
$$;

revoke all on function public.cancelar_financeiro_recorrencia(bigint) from public, anon;
grant execute on function public.cancelar_financeiro_recorrencia(bigint) to authenticated;
