begin;

create sequence if not exists public.equipamento_emprestimos_numero_seq;

create table if not exists public.cliente_unidades (
  id bigint generated by default as identity primary key,
  cliente_id bigint not null references public.clientes(id) on delete cascade,
  nome text not null,
  cidade text not null default '',
  uf text not null default '',
  endereco text not null default '',
  principal boolean not null default false,
  ativo boolean not null default true,
  criado_por uuid not null references auth.users(id) on delete restrict default auth.uid(),
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now(),
  constraint cliente_unidades_nome_check check (btrim(nome) <> '')
);

create unique index if not exists cliente_unidades_cliente_nome_uidx
  on public.cliente_unidades(cliente_id, lower(btrim(nome)));
create unique index if not exists cliente_unidades_principal_uidx
  on public.cliente_unidades(cliente_id) where principal and ativo;
create index if not exists cliente_unidades_cliente_ativo_idx
  on public.cliente_unidades(cliente_id, ativo);

insert into public.cliente_unidades(cliente_id,nome,cidade,uf,endereco,principal,criado_por)
select c.id, coalesce(nullif(btrim(c.unidade),''),'Matriz'), coalesce(c.cidade,''), coalesce(c.uf,''),
       coalesce(c.endereco,''), true,
       coalesce((select p.user_id from public.perfis_usuarios p where p.ativo order by p.criado_em limit 1),
                (select u.id from auth.users u order by u.created_at limit 1))
from public.clientes c
where not exists (select 1 from public.cliente_unidades u where u.cliente_id=c.id)
  and exists (select 1 from auth.users);

alter table public.equipamentos add column if not exists proprietario_tipo text not null default 'Cliente';
-- Mantido como identificador sem uma segunda FK para clientes: evita ambiguidade
-- nas consultas PostgREST já existentes, que usam cliente_id como localização atual.
alter table public.equipamentos add column if not exists proprietario_cliente_id bigint;
alter table public.equipamentos add column if not exists unidade_id bigint references public.cliente_unidades(id) on delete set null;
alter table public.equipamentos add column if not exists responsavel_nome text not null default '';
alter table public.equipamentos add column if not exists condicao text not null default 'Bom';
alter table public.equipamentos add column if not exists acessorios text not null default '';

update public.equipamentos
set proprietario_tipo=case when cliente_id is null then 'Help' else 'Cliente' end,
    proprietario_cliente_id=cliente_id
where proprietario_cliente_id is null;

update public.equipamentos e
set unidade_id=u.id
from public.cliente_unidades u
where e.unidade_id is null and e.cliente_id=u.cliente_id and u.principal;

do $$ begin
  alter table public.equipamentos add constraint equipamentos_proprietario_tipo_check
    check (proprietario_tipo in ('Help','Cliente'));
exception when duplicate_object then null; end $$;

create index if not exists equipamentos_proprietario_idx on public.equipamentos(proprietario_tipo, proprietario_cliente_id);
create index if not exists equipamentos_unidade_idx on public.equipamentos(unidade_id);
create index if not exists equipamentos_status_emprestado_idx on public.equipamentos(status, emprestado);

create table if not exists public.equipamento_emprestimos (
  id bigint generated by default as identity primary key,
  numero text not null unique default ('EMP-' || to_char(current_date,'YYYY') || '-' || lpad(nextval('public.equipamento_emprestimos_numero_seq')::text,5,'0')),
  equipamento_id bigint not null references public.equipamentos(id) on delete restrict,
  cliente_id bigint not null references public.clientes(id) on delete restrict,
  unidade_id bigint references public.cliente_unidades(id) on delete set null,
  os_id bigint references public.ordens_servico(id) on delete set null,
  responsavel_nome text not null,
  motivo text not null default '',
  data_saida timestamptz not null default now(),
  previsao_devolucao date,
  devolvido_em timestamptz,
  status text not null default 'Ativo',
  condicao_saida text not null default 'Bom',
  condicao_retorno text not null default '',
  acessorios_saida text not null default '',
  acessorios_retorno text not null default '',
  observacoes text not null default '',
  criado_por uuid not null references auth.users(id) on delete restrict default auth.uid(),
  devolvido_por uuid references auth.users(id) on delete set null,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now(),
  constraint equipamento_emprestimos_status_check check (status in ('Ativo','Aguardando devolução','Devolvido','Cancelado')),
  constraint equipamento_emprestimos_responsavel_check check (btrim(responsavel_nome) <> '')
);

create unique index if not exists equipamento_emprestimos_ativo_uidx
  on public.equipamento_emprestimos(equipamento_id)
  where status in ('Ativo','Aguardando devolução');
create index if not exists equipamento_emprestimos_cliente_idx on public.equipamento_emprestimos(cliente_id, status);
create index if not exists equipamento_emprestimos_unidade_idx on public.equipamento_emprestimos(unidade_id);
create index if not exists equipamento_emprestimos_os_idx on public.equipamento_emprestimos(os_id);
create index if not exists equipamento_emprestimos_previsao_idx on public.equipamento_emprestimos(previsao_devolucao) where status in ('Ativo','Aguardando devolução');

create table if not exists public.equipamento_movimentacoes (
  id bigint generated by default as identity primary key,
  equipamento_id bigint not null references public.equipamentos(id) on delete restrict,
  emprestimo_id bigint references public.equipamento_emprestimos(id) on delete set null,
  cliente_id bigint references public.clientes(id) on delete set null,
  unidade_id bigint references public.cliente_unidades(id) on delete set null,
  os_id bigint references public.ordens_servico(id) on delete set null,
  tipo text not null,
  origem text not null default '',
  destino text not null default '',
  status_anterior text not null default '',
  status_novo text not null default '',
  responsavel_nome text not null default '',
  condicao text not null default '',
  acessorios text not null default '',
  descricao text not null default '',
  usuario_id uuid not null references auth.users(id) on delete restrict default auth.uid(),
  ocorrido_em timestamptz not null default now(),
  constraint equipamento_movimentacoes_tipo_check check (btrim(tipo) <> '')
);

create index if not exists equipamento_movimentacoes_equipamento_idx on public.equipamento_movimentacoes(equipamento_id, ocorrido_em desc);
create index if not exists equipamento_movimentacoes_emprestimo_idx on public.equipamento_movimentacoes(emprestimo_id);
create index if not exists equipamento_movimentacoes_cliente_idx on public.equipamento_movimentacoes(cliente_id);
create index if not exists equipamento_movimentacoes_os_idx on public.equipamento_movimentacoes(os_id);

create or replace function public.validar_estado_emprestimo_equipamento()
returns trigger language plpgsql security invoker set search_path='' as $$
declare v_ativo boolean;
begin
  select exists(
    select 1 from public.equipamento_emprestimos
    where equipamento_id=new.id and status in ('Ativo','Aguardando devolução')
  ) into v_ativo;
  if (new.emprestado or new.status='Emprestado') and not v_ativo then
    raise exception 'Use a ação Emprestar reserva para marcar uma máquina como emprestada.';
  end if;
  if v_ativo and (not new.emprestado or new.status<>'Emprestado') then
    raise exception 'Receba a devolução antes de alterar o estado desta máquina.';
  end if;
  return new;
end $$;

drop trigger if exists validar_estado_emprestimo_equipamento_trg on public.equipamentos;
create trigger validar_estado_emprestimo_equipamento_trg
before insert or update of emprestado,status on public.equipamentos
for each row execute function public.validar_estado_emprestimo_equipamento();

alter table public.cliente_unidades enable row level security;
alter table public.equipamento_emprestimos enable row level security;
alter table public.equipamento_movimentacoes enable row level security;

revoke all on public.cliente_unidades, public.equipamento_emprestimos, public.equipamento_movimentacoes from anon;
grant select,insert,update on public.cliente_unidades, public.equipamento_emprestimos to authenticated;
grant select,insert on public.equipamento_movimentacoes to authenticated;
grant usage,select on sequence public.equipamento_emprestimos_numero_seq to authenticated;
grant usage,select on all sequences in schema public to authenticated;

drop policy if exists "Equipe visualiza unidades" on public.cliente_unidades;
create policy "Equipe visualiza unidades" on public.cliente_unidades for select to authenticated
using ((select private.crm_tem_permissao('clientes')) or (select private.crm_tem_permissao('os')));
drop policy if exists "Equipe cria unidades" on public.cliente_unidades;
create policy "Equipe cria unidades" on public.cliente_unidades for insert to authenticated
with check (((select private.crm_tem_permissao('crm')) or (select private.crm_tem_permissao('osCriar')) or (select private.crm_tem_permissao('osEditar'))) and criado_por=(select auth.uid()));
drop policy if exists "Equipe atualiza unidades" on public.cliente_unidades;
create policy "Equipe atualiza unidades" on public.cliente_unidades for update to authenticated
using ((select private.crm_tem_permissao('crm')) or (select private.crm_tem_permissao('osCriar')) or (select private.crm_tem_permissao('osEditar')))
with check ((select private.crm_tem_permissao('crm')) or (select private.crm_tem_permissao('osCriar')) or (select private.crm_tem_permissao('osEditar')));

drop policy if exists "Equipe visualiza emprestimos" on public.equipamento_emprestimos;
create policy "Equipe visualiza emprestimos" on public.equipamento_emprestimos for select to authenticated
using ((select private.crm_tem_permissao('os')));
drop policy if exists "Equipe cria emprestimos" on public.equipamento_emprestimos;
create policy "Equipe cria emprestimos" on public.equipamento_emprestimos for insert to authenticated
with check (((select private.crm_tem_permissao('osCriar')) or (select private.crm_tem_permissao('osEditar'))) and criado_por=(select auth.uid()));
drop policy if exists "Equipe atualiza emprestimos" on public.equipamento_emprestimos;
create policy "Equipe atualiza emprestimos" on public.equipamento_emprestimos for update to authenticated
using ((select private.crm_tem_permissao('osEditar')))
with check ((select private.crm_tem_permissao('osEditar')));

drop policy if exists "Equipe visualiza movimentacoes de equipamentos" on public.equipamento_movimentacoes;
create policy "Equipe visualiza movimentacoes de equipamentos" on public.equipamento_movimentacoes for select to authenticated
using ((select private.crm_tem_permissao('os')));
drop policy if exists "Equipe registra movimentacoes de equipamentos" on public.equipamento_movimentacoes;
create policy "Equipe registra movimentacoes de equipamentos" on public.equipamento_movimentacoes for insert to authenticated
with check (((select private.crm_tem_permissao('osCriar')) or (select private.crm_tem_permissao('osEditar'))) and usuario_id=(select auth.uid()));

create or replace function public.salvar_cliente_unidade(
  p_id bigint, p_cliente_id bigint, p_nome text, p_cidade text, p_uf text,
  p_endereco text, p_principal boolean, p_ativo boolean
)
returns bigint language plpgsql security invoker set search_path='' as $$
declare v_id bigint;
begin
  if (select auth.uid()) is null or not (private.crm_tem_permissao('crm') or private.crm_tem_permissao('osCriar') or private.crm_tem_permissao('osEditar')) then
    raise exception 'Você não possui permissão para alterar filiais.' using errcode='42501';
  end if;
  if nullif(btrim(p_nome),'') is null then raise exception 'Informe o nome da filial.'; end if;
  if coalesce(p_principal,false) then update public.cliente_unidades set principal=false,atualizado_em=now() where cliente_id=p_cliente_id and id is distinct from p_id; end if;
  if p_id is null then
    insert into public.cliente_unidades(cliente_id,nome,cidade,uf,endereco,principal,ativo,criado_por)
    values(p_cliente_id,btrim(p_nome),coalesce(btrim(p_cidade),''),upper(coalesce(btrim(p_uf),'')),coalesce(btrim(p_endereco),''),coalesce(p_principal,false),coalesce(p_ativo,true),(select auth.uid()))
    returning id into v_id;
  else
    update public.cliente_unidades set nome=btrim(p_nome),cidade=coalesce(btrim(p_cidade),''),uf=upper(coalesce(btrim(p_uf),'')),endereco=coalesce(btrim(p_endereco),''),principal=coalesce(p_principal,false),ativo=coalesce(p_ativo,true),atualizado_em=now()
    where id=p_id and cliente_id=p_cliente_id returning id into v_id;
    if v_id is null then raise exception 'Filial não encontrada ou sem permissão.'; end if;
  end if;
  return v_id;
end $$;

create or replace function public.movimentar_equipamento(
  p_equipamento_id bigint, p_tipo text, p_origem text, p_destino text,
  p_cliente_id bigint, p_unidade_id bigint, p_os_id bigint, p_status_novo text,
  p_responsavel_nome text, p_condicao text, p_acessorios text, p_descricao text
)
returns bigint language plpgsql security invoker set search_path='' as $$
declare e public.equipamentos%rowtype; v_mov bigint; v_cliente_nome text;
begin
  if (select auth.uid()) is null or not (private.crm_tem_permissao('osCriar') or private.crm_tem_permissao('osEditar')) then
    raise exception 'Você não possui permissão para movimentar equipamentos.' using errcode='42501';
  end if;
  select * into e from public.equipamentos where id=p_equipamento_id for update;
  if not found then raise exception 'Equipamento não encontrado.'; end if;
  if e.emprestado then raise exception 'Este equipamento possui empréstimo ativo. Finalize a devolução antes de movimentá-lo.'; end if;
  select nome into v_cliente_nome from public.clientes where id=p_cliente_id;
  update public.equipamentos set
    cliente_id=p_cliente_id, cliente_nome=coalesce(v_cliente_nome,case when e.proprietario_tipo='Help' then 'Estoque interno' else e.cliente_nome end),
    unidade_id=p_unidade_id, localizacao=coalesce(nullif(btrim(p_destino),''),localizacao),
    status=coalesce(nullif(btrim(p_status_novo),''),status), responsavel_nome=coalesce(btrim(p_responsavel_nome),''),
    condicao=coalesce(nullif(btrim(p_condicao),''),condicao), acessorios=coalesce(btrim(p_acessorios),''), atualizado_em=now()
  where id=e.id;
  insert into public.equipamento_movimentacoes(equipamento_id,cliente_id,unidade_id,os_id,tipo,origem,destino,status_anterior,status_novo,responsavel_nome,condicao,acessorios,descricao,usuario_id)
  values(e.id,p_cliente_id,p_unidade_id,p_os_id,btrim(p_tipo),coalesce(btrim(p_origem),''),coalesce(btrim(p_destino),''),e.status,coalesce(nullif(btrim(p_status_novo),''),e.status),coalesce(btrim(p_responsavel_nome),''),coalesce(btrim(p_condicao),''),coalesce(btrim(p_acessorios),''),coalesce(btrim(p_descricao),''),(select auth.uid()))
  returning id into v_mov;
  return v_mov;
end $$;

create or replace function public.registrar_emprestimo_equipamento(
  p_equipamento_id bigint, p_cliente_id bigint, p_unidade_id bigint, p_os_id bigint,
  p_responsavel_nome text, p_previsao_devolucao date, p_motivo text,
  p_condicao_saida text, p_acessorios_saida text, p_observacoes text
)
returns bigint language plpgsql security invoker set search_path='' as $$
declare e public.equipamentos%rowtype; v_id bigint; v_cliente text; v_unidade text;
begin
  if (select auth.uid()) is null or not (private.crm_tem_permissao('osCriar') or private.crm_tem_permissao('osEditar')) then
    raise exception 'Você não possui permissão para emprestar equipamentos.' using errcode='42501';
  end if;
  if nullif(btrim(p_responsavel_nome),'') is null then raise exception 'Informe o responsável pelo equipamento.'; end if;
  select * into e from public.equipamentos where id=p_equipamento_id for update;
  if not found then raise exception 'Equipamento não encontrado.'; end if;
  if e.proprietario_tipo <> 'Help' then raise exception 'Somente máquinas da Help podem ser emprestadas como reserva.'; end if;
  if e.status <> 'Disponível no almoxarifado' then raise exception 'A máquina precisa estar disponível no almoxarifado antes do empréstimo.'; end if;
  if e.emprestado or exists(select 1 from public.equipamento_emprestimos where equipamento_id=e.id and status in ('Ativo','Aguardando devolução')) then raise exception 'Este equipamento já possui empréstimo ativo.'; end if;
  select nome into v_cliente from public.clientes where id=p_cliente_id;
  if v_cliente is null then raise exception 'Cliente não encontrado.'; end if;
  select nome into v_unidade from public.cliente_unidades where id=p_unidade_id and cliente_id=p_cliente_id and ativo;
  insert into public.equipamento_emprestimos(equipamento_id,cliente_id,unidade_id,os_id,responsavel_nome,motivo,previsao_devolucao,condicao_saida,acessorios_saida,observacoes,criado_por)
  values(e.id,p_cliente_id,p_unidade_id,p_os_id,btrim(p_responsavel_nome),coalesce(btrim(p_motivo),''),p_previsao_devolucao,coalesce(nullif(btrim(p_condicao_saida),''),e.condicao),coalesce(btrim(p_acessorios_saida),''),coalesce(btrim(p_observacoes),''),(select auth.uid()))
  returning id into v_id;
  update public.equipamentos set cliente_id=p_cliente_id,cliente_nome=v_cliente,unidade_id=p_unidade_id,status='Emprestado',emprestado=true,localizacao=v_cliente||coalesce(' · '||nullif(v_unidade,''),''),responsavel_nome=btrim(p_responsavel_nome),condicao=coalesce(nullif(btrim(p_condicao_saida),''),e.condicao),acessorios=coalesce(btrim(p_acessorios_saida),''),atualizado_em=now() where id=e.id;
  insert into public.equipamento_movimentacoes(equipamento_id,emprestimo_id,cliente_id,unidade_id,os_id,tipo,origem,destino,status_anterior,status_novo,responsavel_nome,condicao,acessorios,descricao,usuario_id)
  values(e.id,v_id,p_cliente_id,p_unidade_id,p_os_id,'Empréstimo',coalesce(nullif(e.localizacao,''),'Almoxarifado Help'),v_cliente||coalesce(' · '||nullif(v_unidade,''),''),e.status,'Emprestado',btrim(p_responsavel_nome),coalesce(nullif(btrim(p_condicao_saida),''),e.condicao),coalesce(btrim(p_acessorios_saida),''),coalesce(btrim(p_motivo),''),(select auth.uid()));
  return v_id;
end $$;

create or replace function public.devolver_emprestimo_equipamento(
  p_emprestimo_id bigint, p_condicao_retorno text, p_acessorios_retorno text,
  p_observacoes text, p_local_retorno text
)
returns bigint language plpgsql security invoker set search_path='' as $$
declare em public.equipamento_emprestimos%rowtype; e public.equipamentos%rowtype;
begin
  if (select auth.uid()) is null or not private.crm_tem_permissao('osEditar') then
    raise exception 'Você não possui permissão para receber devoluções.' using errcode='42501';
  end if;
  select * into em from public.equipamento_emprestimos where id=p_emprestimo_id and status in ('Ativo','Aguardando devolução') for update;
  if not found then raise exception 'Empréstimo ativo não encontrado.'; end if;
  select * into e from public.equipamentos where id=em.equipamento_id for update;
  update public.equipamento_emprestimos set status='Devolvido',devolvido_em=now(),devolvido_por=(select auth.uid()),condicao_retorno=coalesce(btrim(p_condicao_retorno),''),acessorios_retorno=coalesce(btrim(p_acessorios_retorno),''),observacoes=concat_ws(E'\n',nullif(observacoes,''),nullif(btrim(p_observacoes),'')),atualizado_em=now() where id=em.id;
  update public.equipamentos set cliente_id=null,cliente_nome='Estoque interno',unidade_id=null,status='Disponível no almoxarifado',emprestado=false,localizacao=coalesce(nullif(btrim(p_local_retorno),''),'Almoxarifado Help'),responsavel_nome='',condicao=coalesce(nullif(btrim(p_condicao_retorno),''),condicao),acessorios=coalesce(btrim(p_acessorios_retorno),''),atualizado_em=now() where id=e.id;
  insert into public.equipamento_movimentacoes(equipamento_id,emprestimo_id,cliente_id,unidade_id,os_id,tipo,origem,destino,status_anterior,status_novo,condicao,acessorios,descricao,usuario_id)
  values(e.id,em.id,em.cliente_id,em.unidade_id,em.os_id,'Devolução',e.localizacao,coalesce(nullif(btrim(p_local_retorno),''),'Almoxarifado Help'),e.status,'Disponível no almoxarifado',coalesce(btrim(p_condicao_retorno),''),coalesce(btrim(p_acessorios_retorno),''),coalesce(btrim(p_observacoes),''),(select auth.uid()));
  return em.id;
end $$;

revoke execute on function public.salvar_cliente_unidade(bigint,bigint,text,text,text,text,boolean,boolean) from public,anon;
revoke execute on function public.movimentar_equipamento(bigint,text,text,text,bigint,bigint,bigint,text,text,text,text,text) from public,anon;
revoke execute on function public.registrar_emprestimo_equipamento(bigint,bigint,bigint,bigint,text,date,text,text,text,text) from public,anon;
revoke execute on function public.devolver_emprestimo_equipamento(bigint,text,text,text,text) from public,anon;
grant execute on function public.salvar_cliente_unidade(bigint,bigint,text,text,text,text,boolean,boolean) to authenticated;
grant execute on function public.movimentar_equipamento(bigint,text,text,text,bigint,bigint,bigint,text,text,text,text,text) to authenticated;
grant execute on function public.registrar_emprestimo_equipamento(bigint,bigint,bigint,bigint,text,date,text,text,text,text) to authenticated;
grant execute on function public.devolver_emprestimo_equipamento(bigint,text,text,text,text) to authenticated;

commit;
