begin;

-- Gestão comercial: mantém compatibilidade com os leads já existentes.
alter table public.leads add column if not exists responsavel_id uuid references auth.users(id) on delete set null;
alter table public.leads add column if not exists cliente_id bigint references public.clientes(id) on delete set null;
alter table public.leads add column if not exists probabilidade integer not null default 10;
alter table public.leads add column if not exists fechamento_previsto date;
alter table public.leads add column if not exists motivo_perda text not null default '';
alter table public.leads add column if not exists perdido_em timestamptz;
alter table public.leads add column if not exists perdido_por uuid references auth.users(id) on delete set null;

do $$ begin
  alter table public.leads add constraint leads_probabilidade_check check (probabilidade between 0 and 100);
exception when duplicate_object then null; end $$;

update public.leads l
set responsavel_id = p.user_id
from public.perfis_usuarios p
where l.responsavel_id is null
  and p.ativo = true
  and lower(trim(p.nome)) = lower(trim(l.responsavel));

update public.leads
set probabilidade = case etapa
  when 'Novo' then 10 when 'Contato' then 20 when 'Demonstração' then 40
  when 'Proposta' then 60 when 'Negociação' then 80 when 'Fechado' then 100 else 10 end
where probabilidade = 10 and etapa <> 'Novo';

create sequence if not exists public.propostas_numero_seq;

create table if not exists public.propostas_comerciais (
  id uuid primary key default gen_random_uuid(),
  numero text not null unique default ('PROP-' || to_char(current_date,'YYYY') || '-' || lpad(nextval('public.propostas_numero_seq')::text,5,'0')),
  cliente_id bigint not null references public.clientes(id) on delete restrict,
  lead_id text references public.leads(id) on delete set null,
  responsavel_id uuid not null references auth.users(id) on delete restrict default auth.uid(),
  titulo text not null default 'Proposta comercial',
  objeto text not null default '',
  validade_ate date not null default (current_date + 15),
  forma_pagamento text not null default 'PIX ou boleto bancário',
  prazo_implantacao_dias integer not null default 15,
  duracao_meses integer not null default 12,
  desconto numeric(14,2) not null default 0,
  valor_total numeric(14,2) not null default 0,
  valor_mensal numeric(14,2) not null default 0,
  observacoes text not null default '',
  status text not null default 'Rascunho',
  contrato_id uuid references public.contratos(id) on delete set null,
  aprovada_em timestamptz,
  convertida_em timestamptz,
  criado_por uuid not null references auth.users(id) on delete restrict default auth.uid(),
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now(),
  constraint propostas_status_check check (status in ('Rascunho','Enviada','Aprovada','Recusada','Vencida','Convertida')),
  constraint propostas_valores_check check (desconto >= 0 and valor_total >= 0 and valor_mensal >= 0),
  constraint propostas_prazos_check check (prazo_implantacao_dias >= 0 and duracao_meses > 0)
);

create table if not exists public.proposta_itens (
  id bigint generated by default as identity primary key,
  proposta_id uuid not null references public.propostas_comerciais(id) on delete cascade,
  tipo text not null default 'Serviço',
  descricao text not null,
  quantidade numeric(12,3) not null default 1,
  valor_unitario numeric(14,2) not null default 0,
  recorrente boolean not null default false,
  ordem integer not null default 0,
  criado_em timestamptz not null default now(),
  constraint proposta_itens_tipo_check check (tipo in ('Software','Serviço','Implantação','Equipamento','Outro')),
  constraint proposta_itens_valores_check check (quantidade > 0 and valor_unitario >= 0)
);

create table if not exists public.comercial_metas (
  id bigint generated by default as identity primary key,
  usuario_id uuid not null references auth.users(id) on delete cascade,
  competencia date not null,
  meta_valor numeric(14,2) not null default 0,
  meta_fechamentos integer not null default 0,
  criado_por uuid not null references auth.users(id) on delete restrict default auth.uid(),
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now(),
  unique(usuario_id, competencia),
  constraint comercial_metas_competencia_check check (competencia = date_trunc('month',competencia)::date),
  constraint comercial_metas_valores_check check (meta_valor >= 0 and meta_fechamentos >= 0)
);

-- Ativos, estoque e garantia reutilizam os equipamentos e as OS atuais.
alter table public.equipamentos add column if not exists status text not null default 'Em uso';
alter table public.equipamentos add column if not exists data_aquisicao date;
alter table public.equipamentos add column if not exists garantia_ate date;
alter table public.equipamentos add column if not exists localizacao text not null default '';
alter table public.equipamentos add column if not exists emprestado boolean not null default false;

create table if not exists public.estoque_itens (
  id bigint generated by default as identity primary key,
  codigo text not null unique,
  descricao text not null,
  categoria text not null default 'Peças',
  unidade text not null default 'UN',
  quantidade numeric(14,3) not null default 0,
  estoque_minimo numeric(14,3) not null default 0,
  custo_medio numeric(14,2) not null default 0,
  preco_venda numeric(14,2) not null default 0,
  ativo boolean not null default true,
  criado_por uuid not null references auth.users(id) on delete restrict default auth.uid(),
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now(),
  constraint estoque_itens_valores_check check (quantidade >= 0 and estoque_minimo >= 0 and custo_medio >= 0 and preco_venda >= 0)
);

create table if not exists public.estoque_movimentos (
  id bigint generated by default as identity primary key,
  item_id bigint not null references public.estoque_itens(id) on delete restrict,
  direcao text not null,
  quantidade numeric(14,3) not null,
  custo_unitario numeric(14,2),
  os_id bigint references public.ordens_servico(id) on delete set null,
  motivo text not null default '',
  criado_por uuid not null references auth.users(id) on delete restrict default auth.uid(),
  criado_em timestamptz not null default now(),
  constraint estoque_movimentos_direcao_check check (direcao in ('Entrada','Saída')),
  constraint estoque_movimentos_quantidade_check check (quantidade > 0)
);

create table if not exists public.equipamento_historico (
  id bigint generated by default as identity primary key,
  equipamento_id bigint not null references public.equipamentos(id) on delete cascade,
  os_id bigint references public.ordens_servico(id) on delete set null,
  tipo text not null,
  descricao text not null,
  usuario_id uuid not null references auth.users(id) on delete restrict default auth.uid(),
  ocorrido_em timestamptz not null default now()
);

alter table public.os_itens add column if not exists estoque_item_id bigint references public.estoque_itens(id) on delete set null;
alter table public.os_itens add column if not exists movimento_estoque_id bigint references public.estoque_movimentos(id) on delete set null;
alter table public.ordens_servico add column if not exists retorno_de_id bigint references public.ordens_servico(id) on delete set null;
alter table public.ordens_servico add column if not exists atendimento_garantia boolean not null default false;
alter table public.processos_internos add column if not exists contrato_id uuid references public.contratos(id) on delete set null;

create or replace function public.atualizar_total_proposta()
returns trigger language plpgsql security invoker set search_path = '' as $$
declare v_id uuid;
begin
  v_id := coalesce(new.proposta_id, old.proposta_id);
  update public.propostas_comerciais p
  set valor_total = greatest(0, coalesce((select sum(i.quantidade*i.valor_unitario) from public.proposta_itens i where i.proposta_id=v_id and not i.recorrente),0)-p.desconto),
      valor_mensal = coalesce((select sum(i.quantidade*i.valor_unitario) from public.proposta_itens i where i.proposta_id=v_id and i.recorrente),0),
      atualizado_em = now()
  where p.id=v_id;
  return coalesce(new,old);
end $$;

drop trigger if exists proposta_itens_recalcular on public.proposta_itens;
create trigger proposta_itens_recalcular after insert or update or delete on public.proposta_itens
for each row execute function public.atualizar_total_proposta();

create or replace function public.movimentar_saldo_estoque()
returns trigger language plpgsql security invoker set search_path = '' as $$
declare v_atual numeric; v_novo numeric;
begin
  select quantidade into v_atual from public.estoque_itens where id=new.item_id for update;
  if v_atual is null then raise exception 'Item de estoque não encontrado.'; end if;
  v_novo := v_atual + case when new.direcao='Entrada' then new.quantidade else -new.quantidade end;
  if v_novo < 0 then raise exception 'Saldo insuficiente no estoque.'; end if;
  update public.estoque_itens set quantidade=v_novo,
    custo_medio=case when new.direcao='Entrada' and new.custo_unitario is not null then new.custo_unitario else custo_medio end,
    atualizado_em=now() where id=new.item_id;
  return new;
end $$;

drop trigger if exists estoque_movimento_aplicar on public.estoque_movimentos;
create trigger estoque_movimento_aplicar before insert on public.estoque_movimentos
for each row execute function public.movimentar_saldo_estoque();

create index if not exists leads_responsavel_id_idx on public.leads(responsavel_id);
create index if not exists leads_cliente_id_idx on public.leads(cliente_id);
create index if not exists leads_fechamento_previsto_idx on public.leads(fechamento_previsto);
create index if not exists propostas_cliente_id_idx on public.propostas_comerciais(cliente_id);
create index if not exists propostas_responsavel_id_idx on public.propostas_comerciais(responsavel_id);
create index if not exists propostas_status_idx on public.propostas_comerciais(status);
create index if not exists propostas_criado_por_idx on public.propostas_comerciais(criado_por);
create index if not exists propostas_lead_id_idx on public.propostas_comerciais(lead_id);
create index if not exists propostas_contrato_id_idx on public.propostas_comerciais(contrato_id);
create index if not exists proposta_itens_proposta_id_idx on public.proposta_itens(proposta_id);
create index if not exists comercial_metas_usuario_competencia_idx on public.comercial_metas(usuario_id,competencia);
create index if not exists comercial_metas_criado_por_idx on public.comercial_metas(criado_por);
create index if not exists estoque_movimentos_item_id_idx on public.estoque_movimentos(item_id);
create index if not exists estoque_movimentos_os_id_idx on public.estoque_movimentos(os_id);
create index if not exists estoque_movimentos_criado_por_idx on public.estoque_movimentos(criado_por);
create index if not exists estoque_itens_criado_por_idx on public.estoque_itens(criado_por);
create index if not exists equipamento_historico_equipamento_id_idx on public.equipamento_historico(equipamento_id);
create index if not exists equipamento_historico_os_id_idx on public.equipamento_historico(os_id);
create index if not exists equipamento_historico_usuario_id_idx on public.equipamento_historico(usuario_id);
create unique index if not exists processos_internos_contrato_onboarding_uidx on public.processos_internos(contrato_id) where contrato_id is not null;

alter table public.propostas_comerciais enable row level security;
alter table public.proposta_itens enable row level security;
alter table public.comercial_metas enable row level security;
alter table public.estoque_itens enable row level security;
alter table public.estoque_movimentos enable row level security;
alter table public.equipamento_historico enable row level security;

drop policy if exists "Comercial visualiza propostas" on public.propostas_comerciais;
create policy "Comercial visualiza propostas" on public.propostas_comerciais for select to authenticated using ((select private.crm_tem_permissao('crm')));
drop policy if exists "Comercial cria propostas" on public.propostas_comerciais;
create policy "Comercial cria propostas" on public.propostas_comerciais for insert to authenticated with check ((select private.crm_tem_permissao('crm')) and criado_por=(select auth.uid()));
drop policy if exists "Comercial atualiza propostas" on public.propostas_comerciais;
create policy "Comercial atualiza propostas" on public.propostas_comerciais for update to authenticated using ((select private.crm_tem_permissao('crm'))) with check ((select private.crm_tem_permissao('crm')));
drop policy if exists "Comercial exclui propostas" on public.propostas_comerciais;
create policy "Comercial exclui propostas" on public.propostas_comerciais for delete to authenticated using ((select private.crm_tem_permissao('crm')));

drop policy if exists "Comercial visualiza itens de propostas" on public.proposta_itens;
create policy "Comercial visualiza itens de propostas" on public.proposta_itens for select to authenticated using ((select private.crm_tem_permissao('crm')) and exists(select 1 from public.propostas_comerciais p where p.id=proposta_id));
drop policy if exists "Comercial cria itens de propostas" on public.proposta_itens;
create policy "Comercial cria itens de propostas" on public.proposta_itens for insert to authenticated with check ((select private.crm_tem_permissao('crm')) and exists(select 1 from public.propostas_comerciais p where p.id=proposta_id));
drop policy if exists "Comercial atualiza itens de propostas" on public.proposta_itens;
create policy "Comercial atualiza itens de propostas" on public.proposta_itens for update to authenticated using ((select private.crm_tem_permissao('crm'))) with check ((select private.crm_tem_permissao('crm')));
drop policy if exists "Comercial exclui itens de propostas" on public.proposta_itens;
create policy "Comercial exclui itens de propostas" on public.proposta_itens for delete to authenticated using ((select private.crm_tem_permissao('crm')));

drop policy if exists "Comercial visualiza metas" on public.comercial_metas;
create policy "Comercial visualiza metas" on public.comercial_metas for select to authenticated using ((select private.crm_tem_permissao('crm')));
drop policy if exists "Administradores gerenciam metas" on public.comercial_metas;
drop policy if exists "Administradores criam metas" on public.comercial_metas;
create policy "Administradores criam metas" on public.comercial_metas for insert to authenticated with check ((select private.crm_tem_permissao('usuarios')) and criado_por=(select auth.uid()));
drop policy if exists "Administradores atualizam metas" on public.comercial_metas;
create policy "Administradores atualizam metas" on public.comercial_metas for update to authenticated using ((select private.crm_tem_permissao('usuarios'))) with check ((select private.crm_tem_permissao('usuarios')));
drop policy if exists "Administradores excluem metas" on public.comercial_metas;
create policy "Administradores excluem metas" on public.comercial_metas for delete to authenticated using ((select private.crm_tem_permissao('usuarios')));

drop policy if exists "Equipe OS visualiza estoque" on public.estoque_itens;
create policy "Equipe OS visualiza estoque" on public.estoque_itens for select to authenticated using ((select private.crm_tem_permissao('os')));
drop policy if exists "Equipe OS gerencia estoque" on public.estoque_itens;
drop policy if exists "Equipe OS cria estoque" on public.estoque_itens;
create policy "Equipe OS cria estoque" on public.estoque_itens for insert to authenticated with check (((select private.crm_tem_permissao('osCriar')) or (select private.crm_tem_permissao('osEditar'))) and criado_por=(select auth.uid()));
drop policy if exists "Equipe OS atualiza estoque" on public.estoque_itens;
create policy "Equipe OS atualiza estoque" on public.estoque_itens for update to authenticated using ((select private.crm_tem_permissao('osCriar')) or (select private.crm_tem_permissao('osEditar'))) with check ((select private.crm_tem_permissao('osCriar')) or (select private.crm_tem_permissao('osEditar')));
drop policy if exists "Equipe OS visualiza movimentos de estoque" on public.estoque_movimentos;
create policy "Equipe OS visualiza movimentos de estoque" on public.estoque_movimentos for select to authenticated using ((select private.crm_tem_permissao('os')));
drop policy if exists "Equipe OS movimenta estoque" on public.estoque_movimentos;
create policy "Equipe OS movimenta estoque" on public.estoque_movimentos for insert to authenticated with check (((select private.crm_tem_permissao('osCriar')) or (select private.crm_tem_permissao('osEditar'))) and criado_por=(select auth.uid()));
drop policy if exists "Equipe OS visualiza histórico de equipamentos" on public.equipamento_historico;
create policy "Equipe OS visualiza histórico de equipamentos" on public.equipamento_historico for select to authenticated using ((select private.crm_tem_permissao('os')));
drop policy if exists "Equipe OS registra histórico de equipamentos" on public.equipamento_historico;
create policy "Equipe OS registra histórico de equipamentos" on public.equipamento_historico for insert to authenticated with check (((select private.crm_tem_permissao('osCriar')) or (select private.crm_tem_permissao('osEditar'))) and usuario_id=(select auth.uid()));

grant select,insert,update,delete on public.propostas_comerciais,public.proposta_itens,public.comercial_metas,public.estoque_itens to authenticated;
grant select,insert on public.estoque_movimentos,public.equipamento_historico to authenticated;
grant usage,select on sequence public.propostas_numero_seq to authenticated;
grant usage,select on all sequences in schema public to authenticated;

commit;
