-- Módulos de Ordens de Serviço e Financeiro do CRM Help Soluções.
-- Pode ser executado novamente com segurança no SQL Editor do Supabase.

create sequence if not exists public.ordens_servico_numero_seq;

create table if not exists public.equipamentos (
  id bigint generated by default as identity primary key,
  cliente_id bigint references public.clientes(id) on delete set null,
  cliente_nome text not null,
  tipo text not null default '',
  marca text not null default '',
  modelo text not null default '',
  serial text not null default '',
  patrimonio text not null default '',
  observacoes text not null default '',
  ativo boolean not null default true,
  criado_por uuid references auth.users(id) on delete set null default auth.uid(),
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

create table if not exists public.ordens_servico (
  id bigint generated by default as identity primary key,
  numero text not null unique default ('OS-' || to_char(now(), 'YYYY') || '-' || lpad(nextval('public.ordens_servico_numero_seq')::text, 5, '0')),
  chamado_id bigint unique references public.chamados(id) on delete set null,
  equipamento_id bigint references public.equipamentos(id) on delete set null,
  cliente text not null,
  unidade text not null default '',
  solicitante text not null default '',
  tecnico text not null default '',
  equipamento text not null default '',
  marca_modelo text not null default '',
  serial text not null default '',
  problema text not null default '',
  diagnostico text not null default '',
  servico_executado text not null default '',
  observacoes text not null default '',
  status text not null default 'Entrada' check (status in ('Entrada','Diagnóstico','Aguardando aprovação','Aprovada','Em execução','Aguardando peça','Pronta','Entregue','Cancelada')),
  prioridade text not null default 'Normal' check (prioridade in ('Normal','Alta')),
  previsao date,
  garantia_dias integer not null default 0 check (garantia_dias >= 0),
  valor_servicos numeric(12,2) not null default 0 check (valor_servicos >= 0),
  valor_pecas numeric(12,2) not null default 0 check (valor_pecas >= 0),
  desconto numeric(12,2) not null default 0 check (desconto >= 0),
  total numeric(12,2) not null default 0 check (total >= 0),
  assinatura_nome text not null default '',
  assinado_em timestamptz,
  criado_por uuid references auth.users(id) on delete set null default auth.uid(),
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

create table if not exists public.os_itens (
  id bigint generated by default as identity primary key,
  os_id bigint not null references public.ordens_servico(id) on delete cascade,
  tipo text not null check (tipo in ('Serviço','Peça')),
  descricao text not null check (char_length(btrim(descricao)) between 1 and 500),
  quantidade numeric(10,2) not null default 1 check (quantidade > 0),
  valor_unitario numeric(12,2) not null default 0 check (valor_unitario >= 0),
  criado_em timestamptz not null default now()
);

create table if not exists public.financeiro_lancamentos (
  id bigint generated by default as identity primary key,
  tipo text not null check (tipo in ('Receber','Pagar')),
  os_id bigint references public.ordens_servico(id) on delete set null,
  descricao text not null check (char_length(btrim(descricao)) between 1 and 500),
  categoria text not null default 'Outros',
  valor numeric(12,2) not null check (valor > 0),
  vencimento date not null,
  status text not null default 'Pendente' check (status in ('Pendente','Pago','Cancelado')),
  forma_pagamento text not null default '',
  pago_em date,
  observacoes text not null default '',
  criado_por uuid references auth.users(id) on delete set null default auth.uid(),
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

create index if not exists equipamentos_cliente_idx on public.equipamentos(cliente_id, cliente_nome);
create index if not exists equipamentos_criado_por_idx on public.equipamentos(criado_por);
create index if not exists ordens_servico_status_previsao_idx on public.ordens_servico(status, previsao);
create index if not exists ordens_servico_equipamento_idx on public.ordens_servico(equipamento_id) where equipamento_id is not null;
create index if not exists ordens_servico_criado_por_idx on public.ordens_servico(criado_por);
create index if not exists os_itens_os_id_idx on public.os_itens(os_id);
create index if not exists financeiro_vencimento_status_idx on public.financeiro_lancamentos(vencimento, status);
create index if not exists financeiro_os_id_idx on public.financeiro_lancamentos(os_id) where os_id is not null;
create index if not exists financeiro_criado_por_idx on public.financeiro_lancamentos(criado_por);

alter table public.equipamentos enable row level security;
alter table public.ordens_servico enable row level security;
alter table public.os_itens enable row level security;
alter table public.financeiro_lancamentos enable row level security;

revoke all on public.equipamentos, public.ordens_servico, public.os_itens, public.financeiro_lancamentos from anon;
grant select, insert, update, delete on public.equipamentos, public.ordens_servico, public.os_itens, public.financeiro_lancamentos to authenticated;
grant usage, select on sequence public.ordens_servico_numero_seq to authenticated;

do $$
declare tabela text;
begin
  foreach tabela in array array['equipamentos','ordens_servico','os_itens','financeiro_lancamentos'] loop
    execute format('drop policy if exists "Equipe ativa gerencia %1$s" on public.%1$I', tabela);
    execute format($policy$
      create policy "Equipe ativa gerencia %1$s" on public.%1$I
      for all to authenticated
      using (exists (select 1 from public.perfis_usuarios p where p.user_id = (select auth.uid()) and p.ativo = true))
      with check (exists (select 1 from public.perfis_usuarios p where p.user_id = (select auth.uid()) and p.ativo = true))
    $policy$, tabela);
  end loop;
end $$;
