-- Processos internos: múltiplos responsáveis, checklist colaborativo e auditoria.
-- Migração idempotente. Mantém processos_internos.responsavel_nome e checklist
-- sincronizados como campos legados para compatibilidade com integrações antigas.

begin;

create table if not exists public.processo_responsaveis (
  processo_id uuid not null references public.processos_internos(id) on delete cascade,
  usuario_id uuid not null references public.perfis_usuarios(user_id) on delete cascade,
  atribuido_por uuid references auth.users(id) on delete set null default auth.uid(),
  atribuido_em timestamptz not null default now(),
  primary key (processo_id, usuario_id)
);

create index if not exists processo_responsaveis_usuario_idx
  on public.processo_responsaveis(usuario_id, processo_id);
create index if not exists processo_responsaveis_atribuido_por_idx
  on public.processo_responsaveis(atribuido_por);

create table if not exists public.processo_checklist_itens (
  id uuid primary key default gen_random_uuid(),
  processo_id uuid not null references public.processos_internos(id) on delete cascade,
  ordem integer not null check (ordem >= 0),
  texto text not null check (char_length(btrim(texto)) between 1 and 500),
  concluido boolean not null default false,
  marcado_por uuid references auth.users(id) on delete set null,
  marcado_por_nome text,
  marcado_em timestamptz,
  alterado_por uuid references auth.users(id) on delete set null,
  alterado_por_nome text,
  alterado_em timestamptz,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now(),
  unique (processo_id, ordem)
);

create index if not exists processo_checklist_itens_processo_idx
  on public.processo_checklist_itens(processo_id, ordem);
create index if not exists processo_checklist_itens_marcado_por_idx
  on public.processo_checklist_itens(marcado_por);
create index if not exists processo_checklist_itens_alterado_por_idx
  on public.processo_checklist_itens(alterado_por);

create table if not exists public.processo_checklist_historico (
  id bigint generated by default as identity primary key,
  processo_id uuid not null references public.processos_internos(id) on delete cascade,
  item_id uuid references public.processo_checklist_itens(id) on delete set null,
  item_texto text not null,
  acao text not null check (acao in ('marcou', 'desmarcou')),
  usuario_id uuid references auth.users(id) on delete set null,
  usuario_nome text not null,
  ocorrido_em timestamptz not null default now()
);

create index if not exists processo_checklist_historico_processo_idx
  on public.processo_checklist_historico(processo_id, ocorrido_em desc);
create index if not exists processo_checklist_historico_item_idx
  on public.processo_checklist_historico(item_id);
create index if not exists processo_checklist_historico_usuario_idx
  on public.processo_checklist_historico(usuario_id, ocorrido_em desc);

-- Preserva os responsáveis antigos, associando pelo nome já salvo no processo.
insert into public.processo_responsaveis (processo_id, usuario_id, atribuido_por, atribuido_em)
select p.id, u.user_id, p.criado_por, p.criado_em
from public.processos_internos p
join public.perfis_usuarios u
  on lower(btrim(u.nome)) = lower(btrim(p.responsavel_nome))
where u.ativo
on conflict (processo_id, usuario_id) do nothing;

-- Se um nome legado não tiver correspondência, mantém o processo utilizável pelo criador ativo.
insert into public.processo_responsaveis (processo_id, usuario_id, atribuido_por, atribuido_em)
select p.id, p.criado_por, p.criado_por, p.criado_em
from public.processos_internos p
join public.perfis_usuarios u on u.user_id = p.criado_por and u.ativo
where not exists (
  select 1 from public.processo_responsaveis r where r.processo_id = p.id
)
on conflict (processo_id, usuario_id) do nothing;

-- Converte o JSON legado em itens relacionais sem apagar o campo antigo.
insert into public.processo_checklist_itens (processo_id, ordem, texto, concluido)
select p.id,
       (item.ordinality - 1)::integer,
       left(btrim(coalesce(item.valor->>'texto', '')), 500),
       coalesce((item.valor->>'concluido')::boolean, false)
from public.processos_internos p
cross join lateral jsonb_array_elements(coalesce(p.checklist, '[]'::jsonb))
  with ordinality as item(valor, ordinality)
where btrim(coalesce(item.valor->>'texto', '')) <> ''
  and not exists (
    select 1 from public.processo_checklist_itens ci where ci.processo_id = p.id
  )
on conflict (processo_id, ordem) do nothing;

create or replace function private.listar_usuarios_ativos_processo()
returns table(user_id uuid, nome text, perfil text)
language sql
stable
security definer
set search_path = ''
as $$
  select p.user_id, coalesce(nullif(btrim(p.nome), ''), split_part(p.email, '@', 1)), p.perfil
  from public.perfis_usuarios p
  where p.ativo
    and (select auth.uid()) is not null
    and private.crm_usuario_ativo()
  order by 2;
$$;

revoke all on function private.listar_usuarios_ativos_processo() from public, anon;
grant execute on function private.listar_usuarios_ativos_processo() to authenticated;

create or replace function public.listar_usuarios_ativos_processo()
returns table(user_id uuid, nome text, perfil text)
language sql
stable
security invoker
set search_path = ''
as $$
  select * from private.listar_usuarios_ativos_processo();
$$;

revoke all on function public.listar_usuarios_ativos_processo() from public, anon;
grant execute on function public.listar_usuarios_ativos_processo() to authenticated;

create or replace function private.crm_usuario_alvo_ativo(p_usuario_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select (select auth.uid()) is not null
    and private.crm_usuario_ativo()
    and exists (
      select 1 from public.perfis_usuarios p
      where p.user_id = p_usuario_id and p.ativo
    );
$$;

revoke all on function private.crm_usuario_alvo_ativo(uuid) from public, anon, authenticated;

create or replace function private.sincronizar_responsavel_nome_processo()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_processo_id uuid := coalesce(new.processo_id, old.processo_id);
  v_nomes text;
begin
  select string_agg(
           coalesce(nullif(btrim(p.nome), ''), split_part(p.email, '@', 1)),
           ' • ' order by coalesce(nullif(btrim(p.nome), ''), split_part(p.email, '@', 1))
         )
    into v_nomes
  from public.processo_responsaveis r
  join public.perfis_usuarios p on p.user_id = r.usuario_id
  where r.processo_id = v_processo_id;

  if v_nomes is not null then
    update public.processos_internos
       set responsavel_nome = v_nomes,
           atualizado_em = now()
     where id = v_processo_id;
  end if;
  return coalesce(new, old);
end;
$$;

revoke all on function private.sincronizar_responsavel_nome_processo() from public, anon, authenticated;
drop trigger if exists trg_sincronizar_responsavel_nome_processo on public.processo_responsaveis;
create trigger trg_sincronizar_responsavel_nome_processo
after insert or delete on public.processo_responsaveis
for each row execute function private.sincronizar_responsavel_nome_processo();

create or replace function private.registrar_alteracao_checklist_processo()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_usuario uuid := (select auth.uid());
  v_nome text;
begin
  if old.concluido is not distinct from new.concluido then
    new.atualizado_em := now();
    return new;
  end if;

  if v_usuario is null or not private.crm_usuario_ativo() then
    raise exception 'Usuário sem permissão para alterar o checklist.' using errcode = '42501';
  end if;

  if not private.crm_tem_permissao('usuarios') and not exists (
    select 1
    from public.processo_responsaveis r
    where r.processo_id = new.processo_id and r.usuario_id = v_usuario
  ) then
    raise exception 'Somente responsáveis ou administradores podem alterar o checklist.' using errcode = '42501';
  end if;

  select coalesce(nullif(btrim(p.nome), ''), split_part(p.email, '@', 1))
    into v_nome
  from public.perfis_usuarios p
  where p.user_id = v_usuario and p.ativo;

  if v_nome is null then
    raise exception 'Perfil ativo não encontrado.' using errcode = '42501';
  end if;

  new.alterado_por := v_usuario;
  new.alterado_por_nome := v_nome;
  new.alterado_em := now();
  new.atualizado_em := now();

  if new.concluido then
    new.marcado_por := v_usuario;
    new.marcado_por_nome := v_nome;
    new.marcado_em := now();
  else
    new.marcado_por := null;
    new.marcado_por_nome := null;
    new.marcado_em := null;
  end if;

  insert into public.processo_checklist_historico
    (processo_id, item_id, item_texto, acao, usuario_id, usuario_nome, ocorrido_em)
  values
    (new.processo_id, new.id, new.texto,
     case when new.concluido then 'marcou' else 'desmarcou' end,
     v_usuario, v_nome, now());

  return new;
end;
$$;

revoke all on function private.registrar_alteracao_checklist_processo() from public, anon, authenticated;
drop trigger if exists trg_registrar_alteracao_checklist_processo on public.processo_checklist_itens;
create trigger trg_registrar_alteracao_checklist_processo
before update on public.processo_checklist_itens
for each row execute function private.registrar_alteracao_checklist_processo();

create or replace function private.sincronizar_checklist_legado_processo()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_processo_id uuid := coalesce(new.processo_id, old.processo_id);
  v_checklist jsonb;
begin
  select coalesce(
           jsonb_agg(
             jsonb_build_object(
               'id', i.id,
               'texto', i.texto,
               'concluido', i.concluido,
               'marcado_por', i.marcado_por,
               'marcado_por_nome', i.marcado_por_nome,
               'marcado_em', i.marcado_em
             ) order by i.ordem
           ),
           '[]'::jsonb
         )
    into v_checklist
  from public.processo_checklist_itens i
  where i.processo_id = v_processo_id;

  update public.processos_internos
     set checklist = v_checklist,
         atualizado_em = now()
   where id = v_processo_id;
  return coalesce(new, old);
end;
$$;

revoke all on function private.sincronizar_checklist_legado_processo() from public, anon, authenticated;
drop trigger if exists trg_sincronizar_checklist_legado_processo on public.processo_checklist_itens;
create trigger trg_sincronizar_checklist_legado_processo
after insert or update or delete on public.processo_checklist_itens
for each row execute function private.sincronizar_checklist_legado_processo();

alter table public.processo_responsaveis enable row level security;
alter table public.processo_checklist_itens enable row level security;
alter table public.processo_checklist_historico enable row level security;

revoke all on table public.processo_responsaveis from anon, authenticated;
revoke all on table public.processo_checklist_itens from anon, authenticated;
revoke all on table public.processo_checklist_historico from anon, authenticated;

grant select, insert, delete on table public.processo_responsaveis to authenticated;
grant select, insert, delete on table public.processo_checklist_itens to authenticated;
grant update (concluido) on table public.processo_checklist_itens to authenticated;
grant select on table public.processo_checklist_historico to authenticated;

drop policy if exists "Equipe ativa visualiza responsáveis de processos" on public.processo_responsaveis;
create policy "Equipe ativa visualiza responsáveis de processos"
on public.processo_responsaveis for select to authenticated
using (private.crm_usuario_ativo());

drop policy if exists "Criador ou admin atribui responsáveis" on public.processo_responsaveis;
create policy "Criador ou admin atribui responsáveis"
on public.processo_responsaveis for insert to authenticated
with check (
  private.crm_usuario_ativo()
  and private.crm_usuario_alvo_ativo(usuario_id)
  and exists (
    select 1 from public.processos_internos p
    where p.id = processo_id
      and (p.criado_por = (select auth.uid()) or private.crm_tem_permissao('usuarios'))
  )
);

drop policy if exists "Criador ou admin remove responsáveis" on public.processo_responsaveis;
create policy "Criador ou admin remove responsáveis"
on public.processo_responsaveis for delete to authenticated
using (
  private.crm_usuario_ativo()
  and exists (
    select 1 from public.processos_internos p
    where p.id = processo_id
      and (p.criado_por = (select auth.uid()) or private.crm_tem_permissao('usuarios'))
  )
);

drop policy if exists "Equipe ativa visualiza checklist de processos" on public.processo_checklist_itens;
create policy "Equipe ativa visualiza checklist de processos"
on public.processo_checklist_itens for select to authenticated
using (private.crm_usuario_ativo());

drop policy if exists "Criador ou admin cria itens de checklist" on public.processo_checklist_itens;
create policy "Criador ou admin cria itens de checklist"
on public.processo_checklist_itens for insert to authenticated
with check (
  private.crm_usuario_ativo()
  and exists (
    select 1 from public.processos_internos p
    where p.id = processo_id
      and (p.criado_por = (select auth.uid()) or private.crm_tem_permissao('usuarios'))
  )
);

drop policy if exists "Responsável ou admin altera checklist" on public.processo_checklist_itens;
create policy "Responsável ou admin altera checklist"
on public.processo_checklist_itens for update to authenticated
using (
  private.crm_usuario_ativo()
  and (
    private.crm_tem_permissao('usuarios')
    or exists (
      select 1 from public.processo_responsaveis r
      where r.processo_id = processo_checklist_itens.processo_id
        and r.usuario_id = (select auth.uid())
    )
  )
)
with check (
  private.crm_usuario_ativo()
  and (
    private.crm_tem_permissao('usuarios')
    or exists (
      select 1 from public.processo_responsaveis r
      where r.processo_id = processo_checklist_itens.processo_id
        and r.usuario_id = (select auth.uid())
    )
  )
);

drop policy if exists "Criador ou admin remove itens de checklist" on public.processo_checklist_itens;
create policy "Criador ou admin remove itens de checklist"
on public.processo_checklist_itens for delete to authenticated
using (
  private.crm_usuario_ativo()
  and exists (
    select 1 from public.processos_internos p
    where p.id = processo_id
      and (p.criado_por = (select auth.uid()) or private.crm_tem_permissao('usuarios'))
  )
);

drop policy if exists "Equipe ativa visualiza histórico do checklist" on public.processo_checklist_historico;
create policy "Equipe ativa visualiza histórico do checklist"
on public.processo_checklist_historico for select to authenticated
using (private.crm_usuario_ativo());

-- O checklist agora só é alterado pela tabela de itens e seus gatilhos.
revoke update on table public.processos_internos from authenticated;
grant update (
  titulo, descricao, frequencia, dias_semana, intervalo_dias,
  proxima_execucao, ultima_execucao, prioridade, status,
  observacoes, atualizado_em
) on table public.processos_internos to authenticated;

drop policy if exists "Equipe ativa atualiza processos" on public.processos_internos;
drop policy if exists "Responsável, criador ou admin atualiza processos" on public.processos_internos;
create policy "Responsável, criador ou admin atualiza processos"
on public.processos_internos for update to authenticated
using (
  private.crm_usuario_ativo()
  and (
    criado_por = (select auth.uid())
    or private.crm_tem_permissao('usuarios')
    or exists (
      select 1 from public.processo_responsaveis r
      where r.processo_id = processos_internos.id
        and r.usuario_id = (select auth.uid())
    )
  )
)
with check (
  private.crm_usuario_ativo()
  and (
    criado_por = (select auth.uid())
    or private.crm_tem_permissao('usuarios')
    or exists (
      select 1 from public.processo_responsaveis r
      where r.processo_id = processos_internos.id
        and r.usuario_id = (select auth.uid())
    )
  )
);

-- Postgres Changes entrega somente linhas autorizadas pelas políticas RLS.
do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'processo_checklist_itens'
  ) then
    execute 'alter publication supabase_realtime add table public.processo_checklist_itens';
  end if;
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'processo_responsaveis'
  ) then
    execute 'alter publication supabase_realtime add table public.processo_responsaveis';
  end if;
end $$;

commit;
